-- hds header_start
--
-- VHDL Architecture MP2_2.AND1.untitled
--
-- Created:
--          by - skim41.stdt (glsn46.ews.uiuc.edu)
--          at - 17:47:54 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY AND1 IS
   PORT( 
      Clk       : IN     std_logic;
      Comp_Out1 : IN     std_logic;
      Valid0    : IN     std_logic;
      tag0match : OUT    std_logic
   );

-- Declarations

END AND1 ;

-- hds interface_end
ARCHITECTURE untitled OF AND1 IS
BEGIN

 vhdl_AND1 : PROCESS(Comp_Out1, Valid0)

 BEGIN

 IF ((Comp_Out1 = '1') AND (Valid0 = '1')) then
     tag0match <= '1' after 1ns;
 ELSE
     tag0match <= '0' after 1ns;
 END IF;

 END PROCESS vhdl_AND1;
   

END untitled;
