-- hds header_start
--
-- VHDL Architecture MP2.RegDest.untitled
--
-- Created:
--          by - skim41.stdt (eesn6.ews.uiuc.edu)
--          at - 00:18:07 09/27/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY DestReg IS
   PORT( 
      Opcode  : IN     LC3b_opcode;
      clk     : IN     std_logic;
      dest    : IN     LC3b_reg;
      RegDest : OUT    LC3b_reg
   );

-- Declarations

END DestReg ;

-- hds interface_end
ARCHITECTURE untitled OF DestReg IS
BEGIN

  vhdl_RegDest : process (opcode, dest)
  begin  
	IF ((Opcode = "0100")or(Opcode = "1111")) then  
            RegDest <= "111" after 1 ns;
	else
	    RegDest <= dest after 1 ns;
	end if;
  end process vhdl_RegDest;
END untitled;
