-- hds header_start
--
-- VHDL Architecture MP1.ADJ9.untitled
--
-- Created:
--          by - ykim29.stdt (glsn24.ews.uiuc.edu)
--          at - 19:51:57 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY ADJ9 IS
   PORT( 
      Opcode     : IN     LC3b_opcode;
      PCoffset11 : IN     LC3b_PCoffset11;
      clk        : IN     std_logic;
      offset9    : IN     LC3b_offset9;
      ADJ9out    : OUT    LC3b_word
   );

-- Declarations

END ADJ9 ;

-- hds interface_end
ARCHITECTURE untitled OF ADJ9 IS
BEGIN
 vhdl_ADJ9 : process (offset9, PCoffset11)
 begin
     IF (Opcode = "0000" OR Opcode = "1110") then
        IF (offset9(8) = '1') then
            ADJ9out <= ("111111" & offset9 & '0') after delay_MUX2;
        ELSE
            ADJ9out <= ("000000" & offset9 & '0') after delay_MUX2;
	end IF;
     ELSIF (Opcode = "0100") then
	IF (PCoffset11(10) = '1') then
            ADJ9out <= ("1111" & PCoffset11 & '0') after delay_MUX2;
        ELSE
            ADJ9out <= ("0000" & PCoffset11 & '0') after delay_MUX2;	   
	end IF;
     end IF; 
 end process vhdl_ADJ9;   
END untitled;
