-- hds header_start
--
-- VHDL Architecture MP1.NZP.untitled
--
-- Created:
--          by - ykim29.stdt (eesn11.ews.uiuc.edu)
--          at - 18:15:02 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY NZP IS
   PORT( 
      GenCCout : IN     LC3b_cc;
      LoadNZP  : IN     std_logic;
      clk      : IN     std_logic;
      n        : OUT    std_logic;
      p        : OUT    std_logic;
      z        : OUT    std_logic
   );

-- Declarations

END NZP ;

-- hds interface_end

ARCHITECTURE untitled OF NZP IS
  signal pre_NZP : std_logic_vector (2 downto 0);
BEGIN
  ------------------------------
  vhdl_NZP : PROCESS (clk, GenCCout)
    ------------------------------
  BEGIN
    if (clk'event and (clk = '1') and (clk'last_value = '0')) then
      if (LoadNZP = '1') then
        pre_NZP <= GenCCout;
      end if;
    end if;
  END PROCESS vhdl_NZP;
  
  n <= pre_NZP(2) after delay_reg;
  z <= pre_NZP(1) after delay_reg;
  p <= pre_NZP(0) after delay_reg;

END untitled;
