-- hds header_start
--
-- VHDL Architecture MP2.ZExt.untitled
--
-- Created:
--          by - skim41.stdt (eesn9.ews.uiuc.edu)
--          at - 02:12:53 09/24/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY ZExt IS
   PORT( 
      F        : IN     LC3b_word;
      Opcode   : IN     LC3b_opcode;
      clk      : IN     std_logic;
      RFMuxout : OUT    LC3b_word
   );

-- Declarations

END ZExt ;

-- hds interface_end
ARCHITECTURE untitled OF ZExt IS
BEGIN
  Zext : PROCESS (Opcode, F)
    ------------------------------
  BEGIN

   IF (Opcode = "0010" ) then
	RFMuxout <= ("00000000" & F(7 downto 0)) after 1 ns;
   ELSE
        RFMuxout <= F after 1 ns;
   End IF;
  END PROCESS ZExt;
END untitled;
