-- hds header_start
--
-- VHDL Entity MP2_2.AND2.generatedInstance
--
-- Created:
--          by - skim41.stdt (glsn46.ews.uiuc.edu)
--          at - 17:19:11 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY AND2 IS
   PORT( 
      Comp_Out2 : IN     std_logic;
      tag1match : OUT    std_logic;
      Valid1    : IN     std_logic;
      Clk       : IN     std_logic
   );

END AND2 ;

-- hds interface_end
-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF AND2 IS 
BEGIN


END generatedInstance;
