-- hds header_start
--
-- VHDL Architecture MP1.GenCC.untitled
--
-- Created:
--          by - ykim29.stdt (eesn11.ews.uiuc.edu)
--          at - 18:13:07 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY GenCC IS
   PORT( 
      RFMuxout : IN     LC3b_word;
      clk      : IN     std_logic;
      GenCCout : OUT    LC3b_cc
   );

-- Declarations

END GenCC ;

-- hds interface_end
ARCHITECTURE untitled OF GenCC IS
BEGIN
  vhdl_GenCC : process (RFMuxout)
  begin    
	IF (RFMuxout = "0000000000000000") then
          GenCCout <= "010" after 6 ns;
        ELSIF (RFMuxout(15) = '1') then
          GenCCout <= "100" after 6 ns;
	ELSE
          GenCCout <= "001" after 6 ns;
        end IF;
  end process vhdl_GenCC;
END untitled;
