-- hds header_start
--
-- VHDL Entity MP2_2.LRU_bit.generatedInstance
--
-- Created:
--          by - skim41.stdt (eesn21.ews.uiuc.edu)
--          at - 02:51:04 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY LRU_bit IS
   PORT( 
      LRUSel     : OUT    std_logic;
      index      : IN     LC3b_index4;
      LRUupdate0 : IN     std_logic;
      LRUupdate1 : IN     std_logic;
      Clk        : IN     std_logic
   );

END LRU_bit ;

-- hds interface_end
-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LRU_bit IS 
BEGIN


END generatedInstance;
