-- hds header_start
--
-- VHDL Entity MP2_2.Mux_2.generatedInstance
--
-- Created:
--          by - skim41.stdt (glsn46.ews.uiuc.edu)
--          at - 17:50:56 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY Mux_2 IS
   PORT( 
      LineSel       : IN     std_logic;
      CacheLine0    : IN     LC3b_CacheLine64;
      Data_cacheout : OUT    LC3b_CacheLine64;
      Cacheline1    : IN     LC3b_CacheLine64;
      Clk           : IN     std_logic
   );

END Mux_2 ;

-- hds interface_end
-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Mux_2 IS 
BEGIN


END generatedInstance;
