-- hds header_start
--
-- VHDL Architecture MP1.StoreMux.untitled
--
-- Created:
--          by - ykim29.stdt (glsn24.ews.uiuc.edu)
--          at - 19:42:16 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY StoreMux IS
   PORT( 
      SrcA        : IN     LC3b_reg;
      StoreSR     : IN     std_logic;
      clk         : IN     std_logic;
      dest        : IN     LC3b_reg;
      StoreMuxout : OUT    LC3b_reg
   );

-- Declarations

END StoreMux ;

-- hds interface_end
ARCHITECTURE untitled OF StoreMux IS
BEGIN
	PROCESS (SrcA, dest, StoreSR)
		variable state : LC3b_reg;
	BEGIN
		case StoreSR is
			when '1' =>
				state := SrcA;
			when '0' =>
				state := dest;
			when others =>
				state := (OTHERS => 'X');
		end case;
		StoreMuxout <= state after delay_MUX2;
	END PROCESS;
END untitled;
