-- hds header_start
--
-- VHDL Architecture MP2_2.LRU_bit.untitled
--
-- Created:
--          by - skim41.stdt (glsn46.ews.uiuc.edu)
--          at - 16:34:01 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY LRU_bit IS
   PORT( 
      Clk       : IN     std_logic;
      index     : IN     LC3b_index4;
      lrusel    : OUT    std_logic;
      Reset_L   : IN     std_logic;
      lruupdate : IN     std_logic;
      lruload   : IN     std_logic
   );

-- Declarations

END LRU_bit ;

-- hds interface_end
ARCHITECTURE untitled OF LRU_bit IS
BEGIN

   -------------------------------------------------------------------
   vhdl_LRU_bit : PROCESS (LRUupdate, LRUload, index, Reset_L) 
   -------------------------------------------------------------------
     TYPE LRU_array IS array (0 to 15) of std_logic;
     VARIABLE LRUvar : LRU_array;
     VARIABLE int_address : integer;
   BEGIN
     int_address := to_integer(unsigned(index));

     IF (RESET_L = '0') then
        For i in 15 downto 0 loop
           LRUvar(i) := '1';
        END loop;

     ELSif (LRUload = '1') then
        LRUvar(int_address) := LRUupdate;
     End if;

     LRUSel <= LRUvar(int_address) after 51ns;
	
     END PROCESS vhdl_LRU_bit;


END untitled;
