-- hds header_start
--
-- VHDL Architecture MP1.ALU.untitled
--
-- Created:
--          by - ykim29.stdt (eesn11.ews.uiuc.edu)
--          at - 18:12:00 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY ALU IS
   PORT( 
      ALUop     : IN     LC3b_aluop;
      ShiftOut  : IN     LC3b_word;
      alumuxout : IN     LC3b_word;
      clk       : IN     std_logic;
      ALUout    : OUT    LC3b_word
   );

-- Declarations

END ALU ;

-- hds interface_end
ARCHITECTURE untitled OF ALU IS
BEGIN
  ----------------------------------------
  vhdl_ALU : PROCESS (Shiftout, ALUMuxout, ALUop)
    ----------------------------------------
    variable Temp_ALUOut : LC3b_word;
  BEGIN
    
    -- check for ALU operation type, and execute
    case ALUop is
      when alu_add =>
        Temp_ALUOut := std_logic_vector(signed(Shiftout) + signed(ALUMuxout));
      when alu_and =>
        Temp_ALUOut := (Shiftout AND ALUMuxout);
      when alu_not =>
        Temp_ALUOut := (Shiftout XOR "1111111111111111");
      when alu_pass =>
        Temp_ALUOut := (Shiftout);
      when alu_pass2 =>
	Temp_ALUOut := (alumuxout);
      when others =>
    end case;

    ALUout <= Temp_ALUOut after delay_ALU;

  END PROCESS vhdl_ALU;

END untitled;
