-- hds header_start
--
-- VHDL Architecture MP1.WordMux2.untitled
--
-- Created:
--          by - ykim29.stdt (glsn45.ews.uiuc.edu)
--          at - 22:23:23 09/07/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY StoreMux1 IS
   PORT( 
      adj6out   : IN     LC3b_word;
      immsel    : IN     std_logic;
      rfbout    : IN     LC3b_word;
      clk       : IN     std_logic;
      alumuxout : OUT    LC3b_word;
      alumuxsel : IN     std_logic
   );

-- Declarations

END StoreMux1 ;

-- hds interface_end
ARCHITECTURE untitled OF StoreMux1 IS
BEGIN
	vhdl_StoreMux1 : PROCESS (RFBout, ADJ6out, immSel, ALUMuxSel)
		variable state : LC3b_word;
	BEGIN
		IF (immsel = '1') then
			alumuxout <= adj6out after delay_MUX2;
		ELSE
		case ALUMuxSel is
			when '0' =>
				state := RFBout;
			when '1' =>
				state := ADJ6out;
			when others =>
				state := (OTHERS => 'X');
		end case;
		ALUMuxout <= state after delay_MUX2;
		end IF;
	END PROCESS vhdl_StoreMux1;
END untitled;