-- hds header_start
--
-- VHDL Architecture MP1.WordMux2.untitled
--
-- Created:
--          by - ykim29.stdt (glsn45.ews.uiuc.edu)
--          at - 22:23:23 09/07/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY WordMux2 IS
   PORT( 
      A   : IN     LC3b_word;
      B   : IN     LC3b_word;
      Sel : IN     std_logic;
      F   : OUT    LC3b_word
   );

-- Declarations

END WordMux2 ;

-- hds interface_end
ARCHITECTURE untitled OF WordMux2 IS
BEGIN
	PROCESS (A, B, Sel)
		variable state : LC3b_word;
	BEGIN
		case Sel is
			when '0' =>
				state := A;
			when '1' =>
				state := B;
			when others =>
				state := (OTHERS => 'X');
		end case;
		F <= state after delay_MUX2;
	END PROCESS;
END untitled;
