-- hds header_start
--
-- VHDL Architecture MP2_2.Mux_4.untitled
--
-- Created:
--          by - skim41.stdt (glsn46.ews.uiuc.edu)
--          at - 17:54:35 10/15/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY Mux_4 IS
   PORT( 
      Clk           : IN     std_logic;
      Data_cacheout : IN     LC3b_CacheLine64;
      offset        : IN     LC3b_offset3;
      Data_wordout  : OUT    LC3b_word
   );

-- Declarations

END Mux_4 ;

-- hds interface_end
ARCHITECTURE untitled OF Mux_4 IS
BEGIN

	PROCESS (Data_cacheout, offset)
		variable state : LC3b_word;
	BEGIN
		case offset is
			when "000" =>
				state := Data_cacheout(15 downto 0);
			when "010" =>
				state := Data_cacheout(31 downto 16);
			when "100" =>
				state := Data_cacheout(47 downto 32);
			when "110" =>
				state := Data_cacheout(63 downto 48);
			when others =>
				state := (OTHERS => 'X');
		end case;
		Data_wordout <= state after delay_MUX4;
	END PROCESS;

END untitled;
