-- hds header_start
--
-- VHDL Architecture MP1.IR.untitled
--
-- Created:
--          by - ykim29.stdt (eesn11.ews.uiuc.edu)
--          at - 18:13:56 09/08/04
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


LIBRARY MP2_2;
USE MP2_2.LC3b_types.all;

ENTITY IR IS
   PORT( 
      LoadIR     : IN     std_logic;
      MDRout     : IN     LC3b_word;
      clk        : IN     std_logic;
      Bit11      : OUT    std_logic;
      IRout      : OUT    LC3b_word;
      Opcode     : OUT    LC3b_opcode;
      PCoffset11 : OUT    LC3b_PCoffset11;
      SrcA       : OUT    LC3b_reg;
      SrcB       : OUT    LC3b_reg;
      dest       : OUT    LC3b_reg;
      imm4       : OUT    LC3b_imm4;
      imm5       : OUT    LC3b_imm5;
      index6     : OUT    LC3b_index6;
      offset9    : OUT    LC3b_offset9;
      trapvect8  : OUT    LC3b_trapvect8
   );

-- Declarations

END IR ;

-- hds interface_end

ARCHITECTURE untitled OF IR IS
  signal val_ir : LC3b_word;
BEGIN
  ------------------------------
  vhdl_Reg_IR : PROCESS (clk, LoadIR, MDRout)
    ------------------------------
  BEGIN
    if (clk'event and (clk = '1') and (clk'last_value = '0')) then
      if (LoadIR = '1') then
        val_ir <= MDRout after delay_reg;
      end if;
    end if;
  END PROCESS vhdl_Reg_IR;

  Opcode <= val_ir(15 downto 12);
  SrcA <= val_ir(8 downto 6);
  SrcB <= val_ir(2 downto 0);
  Dest <= val_ir(11 downto 9);
  offset9 <= val_ir(8 downto 0);
  index6 <= val_ir(5 downto 0);
  imm4 <= val_ir(3 downto 0);
  imm5 <= val_ir(4 downto 0);
  IRout <= val_ir(15 downto 0);
  PCoffset11 <= val_ir(10 downto 0);
  trapvect8 <= val_ir(7 downto 0);
  Bit11 <= val_ir(11);

END untitled;